theme: jekyll-theme-cayman
title: Pink is The New Evil!
description: A top down whack a mole game!
github:
  installer_url: https://github.com/Jamsers/Pink-is-The-New-Evil/releases/download/v1.1.0.0/PinkIsTheNewEvil_Installer.exe
