theme: jekyll-theme-cayman
title: "Pink is The New Evil!"
description: "A top down whack a mole game!"
tagline: "Pink is The New Evil!"
github:
  installer_url: https://github.com/Jamsers/Pink-is-The-New-Evil/releases/download/v0.99/PinkIsTheNewEvil_Installer.exe
